image: node:18

pages:
  stage: deploy
  variables:
    NEXT_PUBLIC_BASE_PATH: "/wavvvvylines" # set to repo name for project pages, or "" for user/group pages
  script:
    - npm install
    - npm run build --workspace personal-website
    - npm run export --workspace personal-website
    - mkdir -p public
    - cp -R apps/personal-website/out/. public/
  artifacts:
    paths:
      - public
  only:
    - main
